### PR TITLE
Fixes the bugs properly

### PR DESCRIPTION
**Pull request by BluCobalt**
proper bug fixes

### CODE REVIEW

**Review by hYdos — APPROVED** [review]
i approv

**Comment by BoogieMonster1O1** [comment]
dontmerge

**Comment by BoogieMonster1O1** [comment]
until i approveth

**Comment by hYdos** [comment]
im waiting...

**Review by BoogieMonster1O1 — APPROVED** [review]

**Review by TheMadHau5 — APPROVED** [review]
boogie says it works (and ss in #showcase)

**Comment by TheMadHau5** [comment]
:tiny_potato:

**Pull request merged**
