### PR TITLE
Command API (v2) and Permissions API skeleton

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
ported from lfapi 0.x :tm:
- [x] Finish Permissions API skeleton
- [x] Add Command API testmod

### CODE REVIEW

**Comment by BluCobalt** [comment]
Build (failed)

**Comment by hYdos** [comment]
We are not importing sponge's command API.

**Comment by BoogieMonster1O1** [comment]
> Build (failed)

its a draft will fix

**Comment by hYdos** [comment]
This is final. We are NOT adding Brigadier OR Sponge.

**Comment by BluCobalt** [comment]
> This is final. We are NOT adding Brigadier OR Sponge.

Why can't we add brigadier?

**Comment by BoogieMonster1O1** [comment]
Ready for review. 
The only thing to be reviewed is the permissions api since the command api had already been accepted into Legacy Fabric API.

**Comment by PseudoDistant** [comment]
@hYdos I think having something like Sponge's command API would make it easier to cross-port mods, as well as abstract them without as many issues or concern code. If Legacy Fabric is going to be adopted anytime soon by more than just enthusiasts, it needs to be made more accessible to the existing modding community. Refusing to make things better for developers will get the project nowhere. I can't name a single developer who looks fondly on the PS3, it was only as big as it was because of its brand.

**Comment by hYdos** [comment]
> @hYdos I think having something like Sponge's command API would make it easier to cross-port mods, as well as abstract them without as many issues or concern code. If Legacy Fabric is going to be adopted anytime soon by more than just enthusiasts, it needs to be made more accessible to the existing modding community. Refusing to make things better for developers will get the project nowhere. I can't name a single developer who looks fondly on the PS3, it was only as big as it was because of its brand.

The Only thing that Boogie wants from this api is the command parser which is a few lines at most. This barely if not at all helps with porting mods from one place to another.

**Comment by PseudoDistant** [comment]
> The Only thing that Boogie wants from this api is the command parser which is a few lines at most. This barely if not at all helps with porting mods from one place to another. If you wanted to share code, your better off adding brigadier to share command code.

@hYdos I mean make the port job easier, mostly. Both Sponge API's command system and Brigadier are more commonly used than legacy vanilla's system. :/

**Comment by hYdos** [comment]
> :/

Well if we are looking to use either Brigadier or Sponge's cmd api, we should probably use Brigadier as you can share alot more code with it than with sponge.

**Comment by PseudoDistant** [comment]
Probably, I'm good either way tbh. I just thought Sponge was a nice compromise since (far as I understand) it'd be easier to implement.

**Comment by hYdos** [comment]
> Probably, I'm good either way tbh. I just thought Sponge was a nice compromise since (far as I understand) it'd be easier to implement.

They are both pretty easy to implement but boogie will just not shut about Sponge.

**Comment by PseudoDistant** [comment]
Oh, that so? Then yea Brigadier would be better.

**Comment by BoogieMonster1O1** [comment]
> > @hYdos I think having something like Sponge's command API would make it easier to cross-port mods, as well as abstract them without as many issues or concern code. If Legacy Fabric is going to be adopted anytime soon by more than just enthusiasts, it needs to be made more accessible to the existing modding community. Refusing to make things better for developers will get the project nowhere. I can't name a single developer who looks fondly on the PS3, it was only as big as it was because of its brand.
> 
> The Only thing that Boogie wants from this api is the command parser which is a few lines at most. This barely if not at all helps with porting mods from one place to another. If you wanted to share code, your better off adding brigadier to share command code.

It is not a few lines at most. Have you even seen the pr
And no brigadier is extremely conc with 1.8.9
I have explained this many times in the past

**Comment by BoogieMonster1O1** [comment]
Commands are being made easier to use with this - each command can be done with a few lines of code. The api also provides a handful (20+) of parsable types while also supporting custom types. The api also provides command completion. 
Moreover, the update to 1.x was primarily to remove registries due to the issues they caused. This means that porting a module back from 0.x shouldn’t be blocked in such a manner. The choice for sponge was made six months ago and we should stick with it. Nobody gets anything out of not having a good working command api.

**Review by ramidzkh — APPROVED** [review]

**Comment by BoogieMonster1O1** [comment]
this pr clones #49 and #49 already has approvals from @hYdos and @BluCobalt

**Review by BluCobalt — APPROVED** [review]

**Review by TheMadHau5 — APPROVED** [review]
booge stop pestering me now

**Comment by hYdos** [comment]
There Is no benefiet to using Sponge's command api as it does not help share code with ports and writing a parser isnt that bad with the minecraft Utility Functions. This PR is useless unless it incorporates brigadier or Vanilla.

**Pull request merged**
