### PR TITLE
Networking API v1

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
mirror of #80 networking api

### CODE REVIEW

**Comment by BoogieMonster1O1** [comment]
:crab:

**Review by BluCobalt — APPROVED** [review]
As far as I can tell this looks fine but please send screenshots ingame so we know it doesnt crash

**Comment by BoogieMonster1O1** [comment]
https://user-images.githubusercontent.com/62552372/111896632-0d904c80-8a41-11eb-8ed7-a66941e69c40.mov

**Comment by BluCobalt** [comment]
epic @DeadlyMC @hYdos pls review

**Comment by BoogieMonster1O1** [comment]
let it die while its still alive

**Pull request closed without merging**
