### PR TITLE
Upload With GitHub Packages

### PR DESCRIPTION
**Pull request by idwtd**
untested

[(reference)](https://docs.github.com/en/actions/language-and-framework-guides/publishing-java-packages-with-gradle#publishing-packages-to-github-packages)

### CODE REVIEW

**Review by hYdos — APPROVED** [review]
looks good to me. never really touched github packages before though

**Comment by BoogieMonster1O1** [comment]
we already have a bintray
could you explain why you think this is necessary?

**Comment by idwtd** [comment]
centralization

**Review by BoogieMonster1O1 — APPROVED** [review]
makes sense.
I don't think we're getting rid of bintray anytime soon though, so I guess we'll have two repositories for artifacts

**Review by shedaniel — CHANGES_REQUESTED** [review]
I don't think we want to do this? Did GitHub remove the need to authenticate to even use their "repo", if not, this is still useless at this stage.

**Comment by idwtd** [comment]
GitHub provides `GITHUB_TOKEN` to authenticate

**Comment by shedaniel** [comment]
I meant the token required to use the repo

**Comment by idwtd** [comment]
nani

**Comment by hYdos** [comment]
stale

**Pull request closed without merging**
