### PR TITLE
Six Fixes

### PR DESCRIPTION
**Pull request by BoogieMonster1O1**
Fixes a few issues and improves content registries

### CODE REVIEW

**Review by hYdos — COMMENTED** [review]
can you provide working screenshots of testmods?

**Comment by BoogieMonster1O1** [comment]
all fixes are dev related :concern:

**Comment by hYdos** [comment]
so? tbf the only example you could give in game is the item stack rendering in the itemgroup api.

**Comment by BoogieMonster1O1** [comment]
> so? tbf the only example you could give in game is the item stack rendering in the itemgroup api.

right i forgot about tht
will do

**Comment by BoogieMonster1O1** [comment]
image

**Review by BluCobalt — APPROVED** [review]
thank you for 🅱epic screenshots

**Review by hYdos — APPROVED** [review]
👍🏻

**Pull request merged**
